# Generated by Django 5.0.6 on 2024-05-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Coffee_type", models.CharField(max_length=220)),
                ("quantity", models.PositiveBigIntegerField(default=0)),
                ("price", models.PositiveIntegerField(default=0)),
                ("discripsion", models.TextField()),
                ("image", models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name="Sales_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                ("price", models.IntegerField(null=True)),
                ("Total_Price", models.IntegerField(null=True)),
                (
                    "menu_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee_shop_app.inventory",
                    ),
                ),
            ],
        ),
    ]
