# Generated by Django 5.0.6 on 2024-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_shop_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=254)),
                ("phone", models.IntegerField(default=0)),
                ("state", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=5000000000)),
            ],
        ),
    ]
