# Generated by Django 5.0.6 on 2024-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_shop_app", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
