# Generated by Django 5.0.6 on 2024-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_shop_app", "0003_contact_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField(default=0)),
                ("No_of_people", models.IntegerField(default=0)),
                ("date", models.DateField(null=True)),
            ],
        ),
    ]
